---
title: "Model calibration"
output:
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r SIR_incidence_data}
source('./deterministic_models/SIR.R')

incidence_data <- incidence_data_SIR()

library(ggplot2)

ggplot(incidence_data, aes(x = time, y = incidence)) +
  geom_line(colour = "lightgrey") +
  geom_point() +
  theme_test()
```


# Fitting one parameter using MCMC assuming normal distribution

```{r}

stan_text <- "
functions {
  real[] SEIR(real t,
            real[] y, // stocks
            real[] params,
            real[] x_r,
            int[] x_i) {
              
      real dydt[3];
      real population;
      real probability;
      real contactsPerInfected;
      real effectiveContacts;
      real IR; // Infection rate
      real RR; // Recovery rate
      
      population          = y[1] + y[2] + y[3];
      probability         = y[1] / population;
      contactsPerInfected = y[2] * params[1]; // effective contacts per person
      
      IR                  = contactsPerInfected * probability;
      RR                  = y[2] / 2; // recovery time
      
      dydt[1] = -IR;
      dydt[2] = IR - RR;
      dydt[3] = RR;
      
      return dydt;
    }
}

data {
  int<lower = 1> n_obs; // Number of weeks sampled
  int<lower = 1> n_params; // Number of model parameters
  int<lower = 1> n_difeq; // Number of differential equations in the system
  real y[n_obs]; 
  real t0; // Initial time point (zero)
  real ts[n_obs]; // Time points that were sampled
}

transformed data {
  real x_r[0];
  int x_i[0];
}

parameters {
  real<lower = 0> params[n_params]; // Model parameters
  real<lower = 0> sigma;
  real<lower = 0> S0; // Initial number of susceptible
}

transformed parameters{
  real y_hat[n_obs, n_difeq]; // Output from the ODE solver
  real y0[n_difeq]; // Initial conditions
  real incidence[n_obs];
    
  y0[1] = S0;
  y0[2] = 1;
  y0[3] = 0;
  
  y_hat = integrate_ode_rk45(SEIR, y0, t0, ts, params, x_r, x_i);
  
  incidence[1] =  y_hat[1, 2] + y_hat[1, 3];
  
  for (i in 1:n_obs-1) {
    incidence[i + 1] = y_hat[i + 1, 2] + y_hat[i + 1, 3] - y_hat[i, 2] - y_hat[i, 3]; 
  }
  
}

model {
  params[1] ~ uniform(0, 500); 
  S0 ~ uniform(0, 20000);
  sigma ~ cauchy( 0 , 2 );
  y ~ normal(incidence, sigma); 
}
"

file_connection <- file("SIR.stan")
writeLines(stan_text, file_connection)
close(file_connection)

library(rstan)

stan_d = list(n_obs    = length(incidence_data$incidence),
              n_params = 1,
              n_difeq  = 3, # number of differential equations
              y        = incidence_data$incidence,
              t0       = 0,
              ts       = 1:30)

# Test / debug the model:
test <- stan("SIR.stan",
            data = stan_d,
            chains = 1, iter = 10)

# Fit and sample from the posterior
posterior <- stan(fit   = test,
                data   = stan_d,
                chains = 1,
                warmup = 1000,
                iter   = 2000,
                cores  = 3)

posterior_df <- as.data.frame(posterior)
colnames(posterior_df) <- make.names(colnames(posterior_df))
g1 <- ggplot(posterior_df, aes(x = params.1.)) + 
  geom_density() +
  geom_vline(aes(xintercept=mean(params.1.)),
            color="blue", linetype="dashed", size=1)

print(g1)

g2 <- ggplot(posterior_df, aes(x = S0)) + 
  geom_density() +
  geom_vline(aes(xintercept=mean(S0)),
            color="blue", linetype="dashed", size=1)

print(g2)


```


